# Generated by Django 5.1.1 on 2024-09-13 16:26

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='male', max_length=6)),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('degree_level', models.CharField(blank=True, max_length=50, null=True)),
                ('enrollment_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('graduation_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
